name: "CI"
on:
  push:
    branches: ["main"]
  pull_request: {}
jobs:
  eslint:
    timeout-minutes: 20
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
  typecheck: 
    timeout-minutes: 20
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Typecheck
        run: yarn typecheck